[2018-01-11 22:20:17] app.INFO: Matched route "{route}". {"route":"login_check","route_parameters":{"_controller":null,"_route":"login_check"},"request_uri":"http://gedimagination/login_check","method":"POST"} []
[2018-01-11 22:20:17] app.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /Users/louis/Documents/racineWeb/silexNegomat/vendor/symfony/security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"gedimaginadmin\" not found. at /Users/louis/Documents/racineWeb/silexNegomat/src/DAO/UserDAO.php:42)"} []
[2018-01-11 22:20:17] app.DEBUG: Authentication failure, redirect triggered. {"failure_path":"/connexion"} []
[2018-01-11 22:20:17] app.DEBUG: < 302 http://gedimagination/connexion [] []
[2018-01-11 22:20:17] app.INFO: Matched route "{route}". {"route":"connexion","route_parameters":{"_controller":"[object] (Closure: {})","_route":"connexion"},"request_uri":"http://gedimagination/connexion","method":"GET"} []
[2018-01-11 22:20:17] app.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-01-11 22:20:17] app.DEBUG: > GET /connexion [] []
[2018-01-11 22:20:17] app.DEBUG: < 200 [] []
[2018-01-11 22:20:22] app.INFO: Matched route "{route}". {"route":"login_check","route_parameters":{"_controller":null,"_route":"login_check"},"request_uri":"http://gedimagination/login_check","method":"POST"} []
[2018-01-11 22:20:23] app.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /Users/louis/Documents/racineWeb/silexNegomat/vendor/symfony/security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"gedimaginadmin\" not found. at /Users/louis/Documents/racineWeb/silexNegomat/src/DAO/UserDAO.php:42)"} []
[2018-01-11 22:20:23] app.DEBUG: Authentication failure, redirect triggered. {"failure_path":"/connexion"} []
[2018-01-11 22:20:23] app.DEBUG: < 302 http://gedimagination/connexion [] []
[2018-01-11 22:20:23] app.INFO: Matched route "{route}". {"route":"connexion","route_parameters":{"_controller":"[object] (Closure: {})","_route":"connexion"},"request_uri":"http://gedimagination/connexion","method":"GET"} []
[2018-01-11 22:20:23] app.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-01-11 22:20:23] app.DEBUG: > GET /connexion [] []
[2018-01-11 22:20:23] app.DEBUG: < 200 [] []
[2018-01-11 22:20:52] app.INFO: Matched route "{route}". {"route":"login_check","route_parameters":{"_controller":null,"_route":"login_check"},"request_uri":"http://gedimagination/login_check","method":"POST"} []
[2018-01-11 22:20:52] app.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /Users/louis/Documents/racineWeb/silexNegomat/vendor/symfony/security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"gedimaginadmin\" not found. at /Users/louis/Documents/racineWeb/silexNegomat/src/DAO/UserDAO.php:42)"} []
[2018-01-11 22:20:52] app.DEBUG: Authentication failure, redirect triggered. {"failure_path":"/connexion"} []
[2018-01-11 22:20:52] app.DEBUG: < 302 http://gedimagination/connexion [] []
[2018-01-11 22:20:52] app.INFO: Matched route "{route}". {"route":"connexion","route_parameters":{"_controller":"[object] (Closure: {})","_route":"connexion"},"request_uri":"http://gedimagination/connexion","method":"GET"} []
[2018-01-11 22:20:52] app.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-01-11 22:20:52] app.DEBUG: > GET /connexion [] []
[2018-01-11 22:20:52] app.DEBUG: < 200 [] []
[2018-01-11 22:22:30] app.INFO: Matched route "{route}". {"route":"login_check","route_parameters":{"_controller":null,"_route":"login_check"},"request_uri":"http://gedimagination/login_check","method":"POST"} []
[2018-01-11 22:22:30] app.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /Users/louis/Documents/racineWeb/silexNegomat/vendor/symfony/security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"gedimaginadmin\" not found. at /Users/louis/Documents/racineWeb/silexNegomat/src/DAO/UserDAO.php:42)"} []
[2018-01-11 22:22:30] app.DEBUG: Authentication failure, redirect triggered. {"failure_path":"/connexion"} []
[2018-01-11 22:22:30] app.DEBUG: < 302 http://gedimagination/connexion [] []
[2018-01-11 22:22:31] app.INFO: Matched route "{route}". {"route":"connexion","route_parameters":{"_controller":"[object] (Closure: {})","_route":"connexion"},"request_uri":"http://gedimagination/connexion","method":"GET"} []
[2018-01-11 22:22:31] app.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-01-11 22:22:31] app.DEBUG: > GET /connexion [] []
[2018-01-11 22:22:31] app.DEBUG: < 200 [] []
[2018-01-11 22:28:19] app.INFO: Matched route "{route}". {"route":"connexion","route_parameters":{"_controller":"[object] (Closure: {})","_route":"connexion"},"request_uri":"http://gedimagination/connexion","method":"GET"} []
[2018-01-11 22:28:19] app.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-01-11 22:28:19] app.DEBUG: > GET /connexion [] []
[2018-01-11 22:28:19] app.DEBUG: < 200 [] []
[2018-01-11 22:28:33] app.INFO: Matched route "{route}". {"route":"login_check","route_parameters":{"_controller":null,"_route":"login_check"},"request_uri":"http://gedimagination/login_check","method":"POST"} []
[2018-01-11 22:28:33] app.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /Users/louis/Documents/racineWeb/silexNegomat/vendor/symfony/security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"gedimaginadmin\" not found. at /Users/louis/Documents/racineWeb/silexNegomat/src/DAO/UserDAO.php:42)"} []
[2018-01-11 22:28:33] app.DEBUG: Authentication failure, redirect triggered. {"failure_path":"/connexion"} []
[2018-01-11 22:28:33] app.DEBUG: < 302 http://gedimagination/connexion [] []
[2018-01-11 22:28:33] app.INFO: Matched route "{route}". {"route":"connexion","route_parameters":{"_controller":"[object] (Closure: {})","_route":"connexion"},"request_uri":"http://gedimagination/connexion","method":"GET"} []
[2018-01-11 22:28:33] app.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-01-11 22:28:33] app.DEBUG: > GET /connexion [] []
[2018-01-11 22:28:33] app.DEBUG: < 200 [] []
